apiVersion: v1
kind: Service
metadata:
  name: blog-astro-service
  namespace: blog-astro
spec:
  selector:
    app: blog-astro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP
